In [2]:
import numpy as np
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
array3

array([1, 2, 3])

## 팬시 인덱싱

In [3]:
array1 = np.arange(1,10)
array2 = array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array3 = array2[[0,1,2],2]
array3

array([3, 6, 9])

In [8]:
array4 = array2[[0,1,2],0:2]
array4

array([[1, 2],
       [4, 5],
       [7, 8]])

In [9]:
array5 = array2[[0,1]]
array5

array([[1, 2, 3],
       [4, 5, 6]])

## 불린 인덱싱

In [10]:
array1 = np.arange(1,10)
# []안에 array1>5 Boolean indexing 적용
array2 = array1[array1 > 5]
print('array1>5 불린 인덱싱 값:', array2)

array1>5 불린 인덱싱 값: [6 7 8 9]


## 행렬 정렬

In [24]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

원본 행렬: [3 1 9 5]


In [25]:
# sort로 정렬
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬행렬:',sort_array1)
print('np.sort()호출 후 반환된 원본행렬:', org_array)

np.sort()호출 후 반환된 정렬행렬: [1 3 5 9]
np.sort()호출 후 반환된 원본행렬: [3 1 9 5]


In [26]:
sort_array2 = org_array.sort()
print('org_array.sort()호출 후 반환된 행렬:', sort_array2)
print('org_array.sort()호출 후 원본 행렬:', org_array)

org_array.sort()호출 후 반환된 행렬: None
org_array.sort()호출 후 원본 행렬: [1 3 5 9]


In [27]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [29]:
array2 = np.array([[8,12],
                  [7,1]])

sort_array2_axis0 = np.sort(array2, axis=0)
print('로우방향으로 정렬:\n', sort_array2_axis0)

sort_array2_axis1 = np.sort(array2, axis=1)
print('컬럼방향으로 정렬:\n', sort_array2_axis1)

로우방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [30]:
org = np.array([3,1,9,5])
sort_indices = np.argsort(org)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [32]:
org = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org)[::-1]
sort_indices_desc

array([2, 3, 0, 1], dtype=int64)

In [33]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score)
print('성적 오름차순 정렬시 score 인덱스:', sort_indices_asc)
print(name[sort_indices_asc])

성적 오름차순 정렬시 score 인덱스: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
